#开发环境
#配置文件示例
server:
  #端口配置
  port: 80

#数据库
spring:
  #mysqlh数据库
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://192.168.1.18:3306/homework_management_system?useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#图片存放目录
image-path: /Users/ervinse/Documents/IdeaProjects/homework_management_system/src/main/resources/upload/

#短信服务配置(示例)
SMS:
  #是否启用短信服务
  enable: false
  #服务地址
  regionId: b7dcc314
  #RAM子账号
  accessKeyId: f80c436f9dec
  secret: a58285f4c03a

#日志配置
logging:
  file:
    name: homework_management_system.log