Spring:
  profiles:
    active: dev
---
#持久层配置
mybatis-plus:
  configuration:
#    开启mybatis-plus日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      #主键策略:雪花算法
      id-type: ASSIGN_ID

  #设置 mapper接口中 自定义方法的sql语句 所对应的XML文件位置
  #(Maven 多模块项目的扫描路径需以classpath*:开头(即加载多个 jar 包下的 XML 文件))
  mapper-locations: classpath*:pers/ervinse/mapper/*.xml

#日志配置
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
#  level:
#    pers: DEBUG
